import { Cormorant_Garamond, Open_Sans } from 'next/font/google'
import "./globals.css";
import Navbar from "./components/Navbar";


const cormorant = Cormorant_Garamond({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-serif',
})

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  variable: '--font-sans',
})
export const metadata = {
  title: "My Caffeine App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cormorant.variable} ${openSans.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
